

export class mock {


    public static resp_uu_false = {
        respObject:
        {
            totalNoOfRecords: 328,
            data: [
                { "id": 15879, "name": "Tensor flow CPA test Campaign", "modifiedTime": 1598248271, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 15879, "name": "Tensor flow CPA test Campaign", "modifiedTime": 1598248271, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 5437, "currencyCode": "USD", "budget": -1.0, "dailyBudget": null, "lifetimeBudget": -1.0, "fcap": 80000, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 87.9825, "startTime": 1598248271, "endTime": 7258118399, "pixelId": 11203, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true },
                { "id": 15577, "name": "TensorFlow CPI Test Campaign", "modifiedTime": 1590480042, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 15577, "name": "TensorFlow CPI Test Campaign", "modifiedTime": 1590480042, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 5437, "currencyCode": "USD", "budget": -1.0, "dailyBudget": null, "lifetimeBudget": -1.0, "fcap": 8, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 177.8953, "startTime": 1590480042, "endTime": 7258118399, "pixelId": null, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true },
                { "id": 11610, "name": "Product Flipkart App Test", "modifiedTime": 1588915182, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 11610, "name": "Product Flipkart App Test", "modifiedTime": 1588915182, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 4100, "currencyCode": "INR", "budget": 21000.0, "dailyBudget": null, "lifetimeBudget": 21000.0, "fcap": 8, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 2396.8342, "startTime": 1398764268, "endTime": 7258118399, "pixelId": 10564, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true },
                { "id": 15113, "name": "abh", "modifiedTime": 1576666480, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 15113, "name": "abh", "modifiedTime": 1576666480, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 7679, "currencyCode": "INR", "budget": -1.0, "dailyBudget": null, "lifetimeBudget": -1.0, "fcap": 8, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 337.8013, "startTime": 1576664651, "endTime": 7258118399, "pixelId": 11442, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true },
                { "id": 14596, "name": "Commission Based Automation", "modifiedTime": 1561360988, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 14596, "name": "Commission Based Automation", "modifiedTime": 1561360988, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 5437, "currencyCode": "USD", "budget": -1.0, "dailyBudget": null, "lifetimeBudget": -1.0, "fcap": 8, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 514.9277, "startTime": 1561360988, "endTime": 7258118399, "pixelId": null, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true }
            ]
        },
        showUU: false,
        respId: "mYBgQBesAw3jU8Zu7aMlzC5Qb7Omnf1v",
        error: null
    };


    public static resp_uu_true = {
        respObject:
        {
            totalNoOfRecords: 328,
            data: [
                { "id": 15879, "name": "Tensor flow CPA test Campaign", "modifiedTime": 1598248271, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 15879, "name": "Tensor flow CPA test Campaign", "modifiedTime": 1598248271, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 5437, "currencyCode": "USD", "budget": -1.0, "dailyBudget": null, "lifetimeBudget": -1.0, "fcap": 80000, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 87.9825, "startTime": 1598248271, "endTime": 7258118399, "pixelId": 11203, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true },
                { "id": 15577, "name": "TensorFlow CPI Test Campaign", "modifiedTime": 1590480042, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 15577, "name": "TensorFlow CPI Test Campaign", "modifiedTime": 1590480042, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 5437, "currencyCode": "USD", "budget": -1.0, "dailyBudget": null, "lifetimeBudget": -1.0, "fcap": 8, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 177.8953, "startTime": 1590480042, "endTime": 7258118399, "pixelId": null, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true },
                { "id": 11610, "name": "Product Flipkart App Test", "modifiedTime": 1588915182, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 11610, "name": "Product Flipkart App Test", "modifiedTime": 1588915182, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 4100, "currencyCode": "INR", "budget": 21000.0, "dailyBudget": null, "lifetimeBudget": 21000.0, "fcap": 8, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 2396.8342, "startTime": 1398764268, "endTime": 7258118399, "pixelId": 10564, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true },
                { "id": 15113, "name": "abh", "modifiedTime": 1576666480, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 15113, "name": "abh", "modifiedTime": 1576666480, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 7679, "currencyCode": "INR", "budget": -1.0, "dailyBudget": null, "lifetimeBudget": -1.0, "fcap": 8, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 337.8013, "startTime": 1576664651, "endTime": 7258118399, "pixelId": 11442, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true },
                { "id": 14596, "name": "Commission Based Automation", "modifiedTime": 1561360988, "modifiedBy": null, "impressions": 0, "clicks": 0, "conversions": 0, "ctr": 0.00, "ctc": 0.00, "cvr": 0.00, "iti": 0.00, "revenue": 0.00, "viewConversions": 0, "clickConversions": 0, "currencyId": "BRL", "installs": 0, "clickInstalls": 0, "impInstalls": 0, "invalidClicks": 0, "advRevenue": 0.00, "roi": 0.00, "impressionUniqUsers": 0, "eligibleUniqUsers": 0, "userReach": 0, "eligibleBids": 0, "bidsPlaced": 0, "erpa": 0.00, "erpc": 0.00, "erpm": 0.00, "erpi": 0.00, "cost": 0.00, "margin": 0.00, "ecpi": 0.00, "ecpa": 0.00, "ecpc": 0.00, "ecpm": 0.00, "day": null, "hour": null, "startTimestamp": null, "endTimestamp": null, "campaign": { "id": 14596, "name": "Commission Based Automation", "modifiedTime": 1561360988, "modifiedBy": null, "active": true, "creationTime": null, "createdBy": null, "licenseeId": 1, "advertiserId": 5437, "currencyCode": "USD", "budget": -1.0, "dailyBudget": null, "lifetimeBudget": -1.0, "fcap": 8, "dailyUserFcap": null, "userFcapDuration": null, "lifetimeUserFcap": null, "daysDuration": -1, "daysElapsed": 514.9277, "startTime": 1561360988, "endTime": 7258118399, "pixelId": null, "cpaTarget": null }, "advertiser": null, "strategy": null, "creative": null, "active": true }
            ]
        },
        showUU: true,
        respId: "mYBgQBesAw3jU8Zu7aMlzC5Qb7Omnf1v",
        error: null
    }


    public static resp_chart_uu_false = {
        respObject:
        {
            totalNoOfRecords: 7,
            data: [
                {
                    "id": 1605398400,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 33,
                    "clicks": 3,
                    "conversions": 0,
                    "ctr": 9.09,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.75,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 17,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.25,
                    "erpm": 22.81,
                    "erpi": 0,
                    "cost": 0.53,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.18,
                    "ecpm": 15.97,
                    "day": 1605398400,
                    "hour": null,
                    "startTimestamp": 1605398400,
                    "endTimestamp": 1605484800,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605744000,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 184,
                    "clicks": 2,
                    "conversions": 0,
                    "ctr": 1.09,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 19.82,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 112,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 9.91,
                    "erpm": 107.71,
                    "erpi": 0,
                    "cost": 13.87,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 6.94,
                    "ecpm": 75.4,
                    "day": 1605744000,
                    "hour": null,
                    "startTimestamp": 1605744000,
                    "endTimestamp": 1605830400,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605225600,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 33,
                    "clicks": 4,
                    "conversions": 0,
                    "ctr": 12.12,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.57,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 13,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.14,
                    "erpm": 17.39,
                    "erpi": 0,
                    "cost": 0.4,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.1,
                    "ecpm": 12.17,
                    "day": 1605225600,
                    "hour": null,
                    "startTimestamp": 1605225600,
                    "endTimestamp": 1605312000,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605484800,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 48,
                    "clicks": 12,
                    "conversions": 0,
                    "ctr": 25,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.7,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 28,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.06,
                    "erpm": 14.66,
                    "erpi": 0,
                    "cost": 0.49,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.04,
                    "ecpm": 10.26,
                    "day": 1605484800,
                    "hour": null,
                    "startTimestamp": 1605484800,
                    "endTimestamp": 1605571200,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605312000,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 19,
                    "clicks": 2,
                    "conversions": 0,
                    "ctr": 10.53,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.94,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 14,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.47,
                    "erpm": 49.48,
                    "erpi": 0,
                    "cost": 0.66,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.33,
                    "ecpm": 34.63,
                    "day": 1605312000,
                    "hour": null,
                    "startTimestamp": 1605312000,
                    "endTimestamp": 1605398400,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605657600,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 109,
                    "clicks": 11,
                    "conversions": 0,
                    "ctr": 10.09,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 11,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 61,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 1,
                    "erpm": 100.89,
                    "erpi": 0,
                    "cost": 7.7,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.7,
                    "ecpm": 70.62,
                    "day": 1605657600,
                    "hour": null,
                    "startTimestamp": 1605657600,
                    "endTimestamp": 1605744000,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605571200,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 52,
                    "clicks": 22,
                    "conversions": 0,
                    "ctr": 42.31,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.51,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 23,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.02,
                    "erpm": 9.83,
                    "erpi": 0,
                    "cost": 0.36,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.02,
                    "ecpm": 6.88,
                    "day": 1605571200,
                    "hour": null,
                    "startTimestamp": 1605571200,
                    "endTimestamp": 1605657600,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                }
            ],
            widgetData: {
                "id": 1605830400,
                "name": null,
                "modifiedTime": null,
                "modifiedBy": null,
                "impressions": 478,
                "clicks": 56,
                "conversions": 0,
                "ctr": 11.72,
                "ctc": 0,
                "cvr": 0,
                "iti": 0,
                "revenue": 34.3,
                "viewConversions": 0,
                "clickConversions": 0,
                "currencyId": "INR",
                "installs": 0,
                "clickInstalls": 0,
                "impInstalls": 0,
                "invalidClicks": 0,
                "advRevenue": 0,
                "roi": 0,
                "impressionUniqUsers": 230,
                "eligibleUniqUsers": 0,
                "userReach": 0,
                "eligibleBids": 0,
                "bidsPlaced": 0,
                "erpa": 0,
                "erpc": 0.61,
                "erpm": 71.75,
                "erpi": 0,
                "cost": 24.01,
                "margin": 30,
                "ecpi": 0,
                "ecpa": 0,
                "ecpc": 0.43,
                "ecpm": 50.22
            },
            showUU: false,

        },

        respId: "mYBgQBesAw3jU8Zu7aMlzC5Qb7Omnf1v",
        error: null
    }

    public static resp_chart_uu_true = {
        respObject:
        {
            totalNoOfRecords: 7,
            data: [
                {
                    "id": 1605398400,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 33,
                    "clicks": 3,
                    "conversions": 0,
                    "ctr": 9.09,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.75,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 17,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.25,
                    "erpm": 22.81,
                    "erpi": 0,
                    "cost": 0.53,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.18,
                    "ecpm": 15.97,
                    "day": 1605398400,
                    "hour": null,
                    "startTimestamp": 1605398400,
                    "endTimestamp": 1605484800,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605744000,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 184,
                    "clicks": 2,
                    "conversions": 0,
                    "ctr": 1.09,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 19.82,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 112,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 9.91,
                    "erpm": 107.71,
                    "erpi": 0,
                    "cost": 13.87,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 6.94,
                    "ecpm": 75.4,
                    "day": 1605744000,
                    "hour": null,
                    "startTimestamp": 1605744000,
                    "endTimestamp": 1605830400,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605225600,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 33,
                    "clicks": 4,
                    "conversions": 0,
                    "ctr": 12.12,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.57,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 13,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.14,
                    "erpm": 17.39,
                    "erpi": 0,
                    "cost": 0.4,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.1,
                    "ecpm": 12.17,
                    "day": 1605225600,
                    "hour": null,
                    "startTimestamp": 1605225600,
                    "endTimestamp": 1605312000,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605484800,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 48,
                    "clicks": 12,
                    "conversions": 0,
                    "ctr": 25,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.7,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 28,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.06,
                    "erpm": 14.66,
                    "erpi": 0,
                    "cost": 0.49,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.04,
                    "ecpm": 10.26,
                    "day": 1605484800,
                    "hour": null,
                    "startTimestamp": 1605484800,
                    "endTimestamp": 1605571200,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605312000,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 19,
                    "clicks": 2,
                    "conversions": 0,
                    "ctr": 10.53,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.94,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 14,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.47,
                    "erpm": 49.48,
                    "erpi": 0,
                    "cost": 0.66,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.33,
                    "ecpm": 34.63,
                    "day": 1605312000,
                    "hour": null,
                    "startTimestamp": 1605312000,
                    "endTimestamp": 1605398400,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605657600,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 109,
                    "clicks": 11,
                    "conversions": 0,
                    "ctr": 10.09,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 11,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 61,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 1,
                    "erpm": 100.89,
                    "erpi": 0,
                    "cost": 7.7,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.7,
                    "ecpm": 70.62,
                    "day": 1605657600,
                    "hour": null,
                    "startTimestamp": 1605657600,
                    "endTimestamp": 1605744000,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                },
                {
                    "id": 1605571200,
                    "name": null,
                    "modifiedTime": null,
                    "modifiedBy": null,
                    "impressions": 52,
                    "clicks": 22,
                    "conversions": 0,
                    "ctr": 42.31,
                    "ctc": 0,
                    "cvr": 0,
                    "iti": 0,
                    "revenue": 0.51,
                    "viewConversions": 0,
                    "clickConversions": 0,
                    "currencyId": "INR",
                    "installs": 0,
                    "clickInstalls": 0,
                    "impInstalls": 0,
                    "invalidClicks": 0,
                    "advRevenue": 0,
                    "roi": 0,
                    "impressionUniqUsers": 23,
                    "eligibleUniqUsers": 0,
                    "userReach": 0,
                    "eligibleBids": 0,
                    "bidsPlaced": 0,
                    "erpa": 0,
                    "erpc": 0.02,
                    "erpm": 9.83,
                    "erpi": 0,
                    "cost": 0.36,
                    "margin": 30,
                    "ecpi": 0,
                    "ecpa": 0,
                    "ecpc": 0.02,
                    "ecpm": 6.88,
                    "day": 1605571200,
                    "hour": null,
                    "startTimestamp": 1605571200,
                    "endTimestamp": 1605657600,
                    "campaign": null,
                    "advertiser": null,
                    "strategy": null,
                    "creative": null,
                    "active": false
                }
            ],
            widgetData: {
                "id": 1605830400,
                "name": null,
                "modifiedTime": null,
                "modifiedBy": null,
                "impressions": 478,
                "clicks": 56,
                "conversions": 0,
                "ctr": 11.72,
                "ctc": 0,
                "cvr": 0,
                "iti": 0,
                "revenue": 34.3,
                "viewConversions": 0,
                "clickConversions": 0,
                "currencyId": "INR",
                "installs": 0,
                "clickInstalls": 0,
                "impInstalls": 0,
                "invalidClicks": 0,
                "advRevenue": 0,
                "roi": 0,
                "impressionUniqUsers": 230,
                "eligibleUniqUsers": 0,
                "userReach": 0,
                "eligibleBids": 0,
                "bidsPlaced": 0,
                "erpa": 0,
                "erpc": 0.61,
                "erpm": 71.75,
                "erpi": 0,
                "cost": 24.01,
                "margin": 30,
                "ecpi": 0,
                "ecpa": 0,
                "ecpc": 0.43,
                "ecpm": 50.22
            },
            showUU: true,
        },
        respId: "mYBgQBesAw3jU8Zu7aMlzC5Qb7Omnf1v",
        error: null
    }




}